//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huella
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiante
    {
        public int id { get; set; }
        public string cui { get; set; }
        public int universidad_id { get; set; }
        public int area_id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string carne { get; set; }
        public string correo { get; set; }
        public byte[] huella { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<bool> estado_huella { get; set; }
    }
}
