//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huella
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario_asignado
    {
        public horario_asignado()
        {
            this.registro = new HashSet<registro>();
        }
    
        public int id { get; set; }
        public int estudiante_id { get; set; }
        public int horario_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual horario horario { get; set; }
        public virtual ICollection<registro> registro { get; set; }
    }
}
