//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huella
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class asistenciaEntities : DbContext
    {
        public asistenciaEntities()
            : base("name=asistenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<estudiante> estudiante { get; set; }
        public DbSet<horario> horario { get; set; }
        public DbSet<horario_asignado> horario_asignado { get; set; }
        public DbSet<registro> registro { get; set; }
        public DbSet<temp_estudiante> temp_estudiante { get; set; }
    }
}
