//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huella
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public int id { get; set; }
        public int horario_asignado_id { get; set; }
        public Nullable<System.TimeSpan> entrada { get; set; }
        public Nullable<System.TimeSpan> salida { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string comentario { get; set; }
        public Nullable<int> estado_comentario { get; set; }
        public Nullable<int> tipo_registro { get; set; }
    
        public virtual horario_asignado horario_asignado { get; set; }
    }
}
